appium/appium-flutter-driver

example/ruby/Gemfile
example/ruby/example.rb
finder/ruby/Gemfile
finder/ruby/README.md
finder/ruby/Rakefile
finder/ruby/appium_flutter_finder.gemspec
finder/ruby/bin/console
finder/ruby/bin/setup
finder/ruby/lib/appium_flutter_finder.rb
finder/ruby/lib/appium_flutter_finder/version.rb
finder/ruby/test/appium_flutter_finder_test.rb
finder/ruby/test/test_helper.rb

example/ruby/example.rb is not enough than Kotlin and JS, but I ensured finder syntax worked.
Actions against elements will be like below. In general, Appium/Selenium element expects users do not handle them from initialisation (`.new`), but we must give `id` as base 64 string. So, I wrapped it as `Appium::Flutter::Element` for like below syntax.
```ruby
element = Appium::Flutter::Element.new(
@driver,
finder: by_text('You have pushed the button this many times:')
)
assert element.text == 'You have pushed the button this many times:'
```

Add Ruby Finder

---

finder/python/README.md
finder/python/appium_flutter_finder/flutter_finder.py
finder/python/setup.py

`b64encode` behaves differently on Python 2 and 3.
As the same as Appium, let me add a workaround

python: fix b64encode error

---

finder/python/appium_flutter_finder/__init__.py
finder/python/setup.py

Fix the import error below in Python finder:
```
(venv3) ~/git/appium-flutter-driver/finder/python (python-finder-fix ✗) $ python
Python 3.9.1 (default, Jan  8 2021, 17:17:43)
[Clang 12.0.0 (clang-1200.0.32.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from appium_flutter_finder import FlutterElement, FlutterFinder
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Volumes/case-sensitive/git/appium-flutter-driver/finder/python/appium_flutter_finder/__init__.py", line 1, in <module>
from flutter_finder import FlutterElement, FlutterFinder
ModuleNotFoundError: No module named 'flutter_finder'
>>>
```

Fix import path for python

---

driver/package.json

This will allow the flutter driver to run from within Appium 2.0. Please advise if platformNames should include something additional besides iOS or Android.

update package.json with appium 2.0 metadata

---

driver/lib/sessions/ios.ts

Fixing the `iproxy` again. 😄  
I have tested locally and it works fine. There might be a race condition in rare case. Sometimea the proxy setup can take a little longer. When that happens the user will still have to retry in 300 seconds. Then it will work again.
I found this [default waiting](https://github.com/truongsinh/appium-flutter-driver/blob/master/driver/lib/sessions/observatory.ts#L11) is quite long. Not sure if there is a reason behind. This can however be overwritten by adding something like `retryBackoffTime=3000` in the desired capabilities. So it is not a big thing if it is documented somewhere.

Fix the iproxy

---

driver/lib/sessions/ios.ts
driver/package.json

In the fact, Appium already has a native communication channel with iOS devices over usbmuxd.
It helps to remove iproxy related dependencies from Appium toolchain.
~~I'll tweak a bit more, but this works like below.~~ <= finished
```
[WD Proxy] Determined the downstream protocol as 'W3C'
[debug] [BaseDriver] Event 'wdaSessionStarted' logged at 1611733324052 (23:42:04 GMT-0800 (Pacific Standard Time))
[debug] [BaseDriver] Event 'wdaStarted' logged at 1611733324052 (23:42:04 GMT-0800 (Pacific Standard Time))
[XCUITest] Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[debug] [BaseDriver] Event 'orientationSet' logged at 1611733324053 (23:42:04 GMT-0800 (Pacific Standard Time))
[debug] …
```

feat: remove iproxy dependencies to reduce deps

---

driver/package.json

Probably no blocking issue to update the base driver?
Only this driver differs from other Appium drivers.

feat: bump appium-base-driver

---

driver/lib/driver.ts
driver/lib/sessions/android.ts
driver/lib/sessions/ios.ts
driver/lib/sessions/session.ts

The current flutter driver does not work only  W3C capabilities like the below:
> {"capabilities":{"alwaysMatch":{"platformName":"android","appium:udid":"emulator-5554","appium:deviceName":"android","appium:automationName":"flutter","appium:app":"path/to/app"}}}
This is because this driver gives only the 1st argument for `createSession`. It is an array and the 3rd argument may have W3C capabilities. This driver must handle it.
I also gives arguments with `...JSON.parse(JSON.stringify(args))` as deep close to avoid overriding the capabilities.
I tested with only W3C, W3C and MJSONWP, and only MJSONWP capabilities. They were able to establish each session well.
I also removed a blocking code, `avd` check, for Android real device testing which did not work well before.

feat: allow to start a session with w3c capabilities

---

driver/lib/sessions/android.ts
driver/lib/sessions/ios.ts

I found current implementation did not call `deleteSession` in Android/iOS drivers when `getObservatoryWsUri` failed.
So, the next will get unexpected errors.
We should ensure to call deleteSession properly then.

fix: ensure to call deletion method in ios/android when observatory failed

---

finder/python/README.md
finder/python/appium_flutter_finder/flutter_finder.py
finder/python/setup.py
finder/python/tests/flutter_finer_tests.py

Fixes https://github.com/truongsinh/appium-flutter-driver/issues/161
https://pypi.org/project/Appium-Flutter-Finder/0.1.4/
---
1. added test code
2. fixed by_ancestor and by_descendant
3. removed whitespace (`separators=(',', ':')`) (This changes itself should not change anything.)

python: fix descendant by ancestor

---

finder/python/appium_flutter_finder/flutter_finder.py
finder/python/tests/flutter_finer_tests.py

Original code of construct command as following:
```
finder = FlutterFinder()
key_finder = finder.by_value_key("video_name_skip")
sub_key_finder = finder.by_value_key("txt_skip")
final_finder = finder.by_descendant(key_finder, sub_key_finder)
ele=FlutterElement(driver, final_finder)
print(ele.text)
```
output:
[debug] [FlutterDriver] Executing Flutter driver command 'getText'
[debug] [FlutterDriver] >>>{"command":"get_text","finderType":"Descendant","matchRoot":false,"of_finderType":"ByValueKey","of_keyValueString":"video_name_skip","of_keyValueType":"String","matching_finderType":"ByValueKey","matching_keyValueString":"txt_skip","matching_keyValueType":"String"}
[debug] [FlutterDriver] <<< {"isError":true,"response":"Uncaught extension error while executing get_text: Null check operator …

modify bug on _by_ancestor_or_descendant function

---

finder/kotlin/build.gradle.kts
finder/kotlin/settings.gradle.kts

The buildScan plugin is no longer supported since Gradle 6.x
Source: https://docs.gradle.com/enterprise/gradle-plugin/

feat: migrate buildScan to gradleEnterprise

---

README.md
driver/lib/commands/execute.ts

We recently need this to support our use case. Seems to be straight forward and working well when I tested locally, but let me know if I missed something here.
Related doc: https://api.flutter.dev/flutter/flutter_driver/FlutterDriver/setTextEntryEmulation.html
Related flutter's code: https://github.com/flutter/flutter/blob/a3fd36a11500643681f302455891b842be1fbb75/packages/flutter_driver/lib/src/common/text.dart#L63-L82

Add support for setTextEntryEmulation

---

README.md
driver/lib/desired-caps.ts
driver/lib/sessions/android.ts
driver/lib/sessions/ios.ts

Maybe this works. I saw a few reported issues that may need `observatoryWsUri` as a capability.
I haven't tested yet.

feat: observatoryWsUri as a capability

---

driver/lib/sessions/observatory.ts

Seems like the VM service message was changed in Dart 2.17 (used by Flutter >= 3.0.0)
https://github.com/dart-lang/sdk/issues/46756
This PR aims to fix this.

Improve processLogToGetobservatory for Flutter >= 3.0.0

---

driver/package.json
example/nodejs/src/index.js
example/ruby/example.rb
example/ruby/example_sample2_ios.rb

Some command raised errors like below:
hm..
```
[debug] [FlutterDriver] Executing Flutter driver command 'execute'
[debug] [FlutterDriver] >>> {"command":"get_render_tree"}
[debug] [FlutterDriver] <<< {"isError":true,"response":"Uncaught extension error while executing get_render_tree: Invalid argument(s): The source must not be null\n#0      int.parse (dart:core/runtime/libintegers_patch.dart:51:25)\n#1      new Command.deserialize (package:flutter_driver/src/common/message.dart:17:46)\n#2      new GetRenderTree.deserialize (package:flutter_driver/src/common/render_tree.dart:13:63)\n#3      new FlutterDriverExtension.<anonymous closure> (package:flutter_driver/src/extension/extension.dart:119:72)\n#4      FlutterDriverExtension.call …
```

chore: update a few in example

---

driver/CHANGELOG.md
driver/lib/commands/execute.ts
driver/lib/commands/execute/scroll.ts
driver/lib/commands/execute/wait.ts

For https://github.com/appium-userland/appium-flutter-driver/issues/319
Not tested yet.
---
This is kind of correct `driver.execute('flutter:waitFor', buttonFinder, {durationMilliseconds: 100})` though.

feat: define durationMilliseconds as ms

---

driver/lib/driver.ts

Fix to https://github.com/appium-userland/appium-flutter-driver/issues/424

Add proxy command for getWindowHandles to work with Appium 2.0 and plugins

---

driver/lib/driver.ts

https://github.com/appium/appium/blob/fa0e853bd00bfcf7a9e6240bef2980d5566813c1/packages/base-driver/lib/basedriver/driver.js#L182
Maybe the original implementation in this repo was wrong, or changed.

fix: this.startNewCommandTimeout argument

---

driver/lib/driver.ts

closes https://github.com/appium-userland/appium-flutter-driver/issues/500
reConnectFlutterDriver will be called after the executeCommand.

feat: make mobile:activateApp behavior same as activateApp

---

README.md
driver/lib/commands/execute.ts

part of https://github.com/appium-userland/appium-flutter-driver/issues/433
With this, users can:
1. Start a session without `app` and `bundleId`
2. Calls `connectObservatoryWsUrl` to wait for an observatory...
3. Start the app under test from another thread...
4. Establish the observatory URL in 3) as 2) result
5. Proceed the test...

feat: expose connectObservatoryWsUrl as a command

---

README.md
driver/CHANGELOG.md
driver/lib/commands/execute.ts
driver/lib/driver.ts
driver/lib/ios/app.ts

Launch the app via the instrument service natively for ios as `flutter:launchApp`.
`mobile:activateApp`  are via XCUITest, so via XCTest API. it is a bit different method

feat: launch app via instrument service for ios only with appium flutter driver

---

.github/workflows/finder-node.js.yml
.github/workflows/finder-python.yml
.github/workflows/nodejs.yml

> [build (18)](https://github.com/appium-userland/appium-flutter-driver/actions/runs/5842567363/job/15843810479)
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, actions/setup-node@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

ci: use v3

---

README.md
driver/lib/desired-caps.ts
driver/lib/sessions/android.ts
driver/lib/sessions/ios.ts
driver/lib/sessions/observatory.ts
driver/lib/sessions/session.ts

The driver was not working properly if remoteAdbHost and adbPort capabilities are provided. this has been fixed.
Also, added the new `forwardingPort` capability, which allows to customize the local port number used to forward traffic to the device under test. Previously this port was the same as the remote one, which might create unexpected conflicts if it was already occupied on the server host.
cc @KazuCocoa

feat: Properly handle port forwarding

---

driver/npm-shrinkwrap.json

No script/environment diff had in the v1.19 and 1.20, but the 1.20 lock file was actually weird. Maybe `npm install` did not work well?
For example, 1.19.0 had
```
"node_modules/@appium/base-driver": {
"version": "9.3.16",
"license": "Apache-2.0",
"dependencies": {
"@appium/support": "^4.1.3",
"@appium/types": "^0.13.2",
"@colors/colors": "1.5.0",
"@types/async-lock": "1.4.0",
"@types/bluebird": "3.5.38",
"@types/express": "4.17.17",
"@types/lodash": "4.14.195",
"@types/method-override": "0.0.32",
"@types/serve-favicon": "2.5.4",
"async-lock": "1.4.0",
"asyncbox": "2.9.4",
"axios": "1.4.0",
"bluebird": "3.7.2",
"body-parser": "1.20.2",
"es6-error": "4.1.1",
"express": "4.18.2",
"http-status-codes": "2.2.0",
"lodash": "4.17.21",
"lru-cache": "7.18.3",
"method-override": "3.0.0",
"morgan": …
```

revert lock

---

driver/lib/sessions/observatory.ts

may help https://github.com/appium/appium-flutter-driver/issues/567
I'll test this later

feat: try the latest observatory url every attempt in connectSocket

---

driver/lib/sessions/observatory.ts

Changed 'server reponse' to 'server response' in the executeElementCommand error. This is a duplicate of an earlier PR I made with some errors in it.

Fixed typo in executeElementCommand 

---

driver/lib/commands/execute/scroll.ts

fix: `scrollUntilVisible` and `scrollUntilTapable` not working correctly

---

driver/lib/driver.ts
driver/lib/platform.ts
driver/lib/sessions/android.ts
driver/lib/sessions/ios.ts
driver/lib/sessions/observatory.ts
driver/lib/sessions/session.ts

I found leftover ports in https://github.com/appium/appium-flutter-driver/issues/617 , we should fix
- Remove the previous port in the retrial
- Remove the current port forward in the deleteSession
For example, current method to do the port forward leftover the used ports, which is bad.
```
% adb  forward --list
D0AA002182JC0202126 tcp:8200 tcp:6790
D0AA002182JC0202126 tcp:41323 tcp:41323
% adb  forward --list
D0AA002182JC0202126 tcp:8200 tcp:6790
D0AA002182JC0202126 tcp:41323 tcp:41323
```
this will be:...
```
% adb  forward --list
D0AA002182JC0202126 tcp:8200 tcp:6790
D0AA002182JC0202126 tcp:39947 tcp:39947
% adb  forward --list
```

fix: leftover portforward

---

driver/lib/sessions/ios.ts
driver/lib/sessions/observatory.ts

e.g. https://github.com/appium/appium-flutter-driver/issues/617
(not fix, just adding more logs)

chore: add logs

---

README.md
driver/package.json

https://github.com/appium/appium-flutter-driver/issues/646
~~This needs to have the flutter driver own's one.~~ <- flutter driver does not have any of this driver-specific host machine env.

feat: add existing checks for android and xcuitest

---

driver/lib/sessions/base64url.ts

```
lib/sessions/base64url.ts:9:5 - error TS2322: Type 'unknown' is not assignable to type 'string'.
9     base64String = input[util.W3C_WEB_ELEMENT_IDENTIFIER];
~~~~~~~~~~~~
```

fix type error

---

driver/lib/commands/execute.ts

This PR propose the support of the getWidgetDiagnostics [Flutter driver method](https://api.flutter.dev/flutter/flutter_driver/FlutterDriver/getWidgetDiagnostics.html) similarly to the getRenderObjectDiagnostics that is already supported.
This method is required to get widget diagnostic data and gives new opportunities to obtain more context from the application under test.

feat: getWidgetDiagnostics support

---

README.md
finder/kotlin/README.md
finder/ruby/README.md

I need to update examples yet, but this is a temporary readme update

docs: readmes

---

driver/lib/driver.ts
driver/lib/sessions/android.ts
driver/lib/sessions/ios.ts
driver/lib/sessions/log-monitor.ts
driver/lib/sessions/observatory.ts
driver/lib/sessions/session.ts
driver/package.json

Instead of checking the syslog buffer, which might be already too fresh, for the observatory URL we use the event-based log monitoring, which is running is the background and check every log line for possible pattern matches. As soon as the matching log line is found the observatory url is remembered and then used to create the socket.
@KazuCocoa Could you please help with testing this?

feat: Introduce proper syslog scanning

---

README.md
driver/CHANGELOG.md
driver/lib/desired-caps.ts
driver/lib/sessions/android.ts
driver/lib/sessions/ios.ts
driver/lib/sessions/log-monitor.ts
driver/lib/sessions/session.ts
driver/package.json
example/ruby/example_sample2.rb
example/ruby/example_sample2_ios.rb

https://github.com/appium/appium-flutter-driver/issues/726

fix: re connect with a new observatory url after an app start

---

README.md
driver/lib/commands/execute.ts
example/dart/drag_commands.dart
example/dart/get_text_command.dart

hi there,
Recently I encountered a problem when getting text from Text widget. Then I tried to fix it by revise code in https://github.com/Alpaca00/command-driven-list, and it worked.
- I described my issue and simple solution to fix it here [Solving getText Issues with Appium Flutter Driver: A Complete Guide](https://medium.com/@tandt53/solving-gettext-issues-with-appium-flutter-driver-a-complete-guide-1b2834da5d32).
- I also found a similar issue in [issue#585](https://github.com/appium/appium-flutter-driver/issues/585). 
Thus, I decided to implement a new command `getTextWithCommandExtension` that is similar with `dragAndDropWithCommandExtension`. It works on my local. 
Please refer to my flutter code [here](https://github.com/Alpaca00/command-driven-list/pull/1) and attached video for …

feat: add getText enhancement for complex text widgets

---

driver/lib/sessions/observatory.ts
example/ruby/example_sample2.rb
example/ruby/example_sample2_ios.rb

I observed the `ext.flutter.driver` module load could take some time, so one time check could fail as the module is not loaded yet.
Closes https://github.com/appium/appium-flutter-driver/issues/619 and https://github.com/appium/appium-flutter-driver/issues/758

fix: wait module load

---

driver/lib/driver.ts
example/ruby/example_sample2.rb
example/ruby/example_sample2_ios.rb

iOS hasn't been handled properly yet
Closes https://github.com/appium/appium-flutter-driver/issues/793

fix: handle orientation command properly for ios

---

README.md
driver/README.md
driver/lib/commands/assertions.ts
driver/lib/commands/execute.ts
driver/lib/commands/execute/scroll.ts
driver/package.json
driver/tsconfig.json
package.json

This PR adds support for custom visibility assertions and utility actions in the appium-flutter-driver, including:
✅ Added Custom Commands:
flutter:assertVisible
flutter:assertNotVisible
flutter:assertTappable
flutter:tap
flutter:click
flutter:getText
flutter:pageBack
flutter:clear
These commands allow clients to:
Verify widget visibility and tappability using Flutter finders (e.g., by key, text, or label, encoded in base64)
Interact with UI elements via tap, click, and clear
Navigate back in the app (pageBack)
Retrieve widget text content (getText)
All commands have been locally tested and validated on real devices with a variety of Flutter widget trees to ensure correct behavior and compatibility..

feat: New Assertions methods and better usability
