appium/appium-flutter-driver

.gitignore
example/python/example.py
example/python/requirement.txt
finder/python/README.md
finder/python/appium_flutter_finder/flutter_finder.py
finder/python/setup.py

https://github.com/truongsinh/appium-flutter-driver/issues/22

Add python

---

driver/lib/sessions/observatory.ts

See https://github.com/truongsinh/appium-flutter-driver/issues/28

attempt to fix "ext.flutter.driver" is not found in "extensionRPCs"

---

driver/package.json

chore(package): update appium-xcuitest-driver to version 3.17.0

---

README.md

Finders look like this after adding this code.

Add content in Finders

---

example/python/example.py

This was my original intention

example: add appium_flutter_finder.flutter_finder

---

finder/python/README.md

https://pypi.org/project/Appium-Flutter-Finder/0.1.3/

py: add 0.1.3 in the changelog

---

driver/lib/sessions/ios.ts

1. This way it will not wait for command to complete and start a thread and proceed further.
2. Then request will send travel through iProxy interface which has already wait for the connection.

Fix: Added spawn to unblock `iProxy` process

---

driver/lib/commands/execute.ts

yesterday, u commit delete param on function waitForCondition, i fixed it..

fix: waitForCondition number of parameters

---

example/ruby/Gemfile
finder/ruby/README.md
finder/ruby/appium_flutter_finder.gemspec
finder/ruby/lib/appium_flutter_finder/version.rb

To match with Appium Ruby binding

feat: bump Ruby dependencies

---

driver/lib/sessions/ios.ts
driver/package.json

This is part of xcuitest-driver to wait for the port is not busy.
I'd like to check if https://github.com/truongsinh/appium-flutter-driver/issues/138 is no busy port stuff first.

chore: try wait for busy

---

example/python/example.py
finder/python/README.md

Added a few examples for Python so people without much Flutter development experience won't have to spend time digging it like me. 
I would appreciate if there are examples for `by_ancestor` and `by_descendant`. But I still don't know how to use that as of today. 😄

Add more examples for python finder.

---

README.md
driver/lib/commands/execute.ts

Hey,
I have added the method for requestData
On my environment it works fine and already deployed to our CI Testing environment.
Thank you for sharing this great repo :-)
Yaniv

Add support for requestData

---

README.md
driver/lib/commands/execute.ts

Added the setFrameSync command based on https://api.flutter.dev/flutter/flutter_driver/SetFrameSync/SetFrameSync.html
Allows the implementation of https://api.flutter.dev/flutter/flutter_driver/FlutterDriver/runUnsynchronized.html in your testing language as I do not know how you would pass a function through to the flutter driver

Added the setFrameSync command

---

README.md
driver/lib/commands/context.ts
driver/lib/driver.ts
driver/lib/sessions/android.ts
driver/lib/sessions/observatory.ts
driver/lib/sessions/session.ts

This PR solves two issues.
WebView: https://github.com/appium-userland/appium-flutter-driver/issues/45
Security flag: https://github.com/appium-userland/appium-flutter-driver/issues/106
For example, the below command worked. `driver.title` in webview context returned the page title.
```
> driver = core.start_driver
=> #<Appium::Core::Base::Driver:0x..fb72ef6553f4607ea browser="unknown">
> driver.title
Selenium::WebDriver::Error::UnknownMethodError: Method has not yet been implemented
from NotYetImplementedError: Method has not yet been implemented
> driver.available_contexts
=> ["NATIVE_APP", "WEBVIEW_com.pichillilorenzo.flutter_browser", "FLUTTER"]
> driver.set_context 'WEBVIEW_com.pichillilorenzo.flutter_browser'
=> nil
> driver.title
=> "Google"
> driver.available_contexts
=> …
```

feat: WebView context via UIA2/XCUITest and allow to pass security flags

---

README.md
finder/nodejs/README.md
finder/nodejs/lib/serializer.ts
finder/nodejs/lib/serializer_test.ts

https://github.com/appium-userland/appium-flutter-driver/pull/167 for JS

fix: fix JS finder of descendant and ancestor

---

driver/lib/driver.ts
driver/lib/sessions/android.ts
driver/lib/sessions/ios.ts
driver/lib/sessions/session.ts
example/ruby/Gemfile
example/ruby/example.rb

https://github.com/appium-userland/appium-flutter-driver/issues/202

feat: add WebView for iOS

---

driver/lib/commands/context.ts
driver/lib/driver.ts
driver/lib/logger.ts
driver/lib/sessions/ios.ts
driver/package.json

https://github.com/appium-userland/appium-flutter-driver/issues/238

feat: update for appium 2

---

example/nodejs/README.md

Addressing https://github.com/appium-userland/appium-flutter-driver/issues/249

update readme to add some steps and clarity

---

example/ruby/Gemfile
example/ruby/example_sample2.rb
example/sample2/README.md

Add anothre sample app as https://github.com/appium-userland/appium-flutter-driver/issues/251 for testing both native_app and flutter contexts.

chore(ruby): add example with sample2 app

---

README.md
driver/lib/commands/execute.ts
driver/lib/driver.ts
driver/lib/sessions/isolate_socket.ts
driver/lib/sessions/observatory.ts

closes https://github.com/appium-userland/appium-flutter-driver/issues/259

feat: observe multiple engines

---

finder/kotlin/build.gradle.kts
finder/kotlin/src/main/kotlin/pro/truongsinh/appium_flutter/finder/ancestor.kt
finder/kotlin/src/main/kotlin/pro/truongsinh/appium_flutter/finder/descendant.kt
finder/kotlin/src/main/kotlin/pro/truongsinh/appium_flutter/finder/serializer.kt
finder/kotlin/src/test/kotlin/pro/truongsinh/appium_flutter/finder/FinderTest.kt

Fix ancestor/descendant maps and their tests

---

driver/lib/commands/execute/scroll.ts

feat: Use waitForTappable in scrollUntilVisible method

---

driver/lib/commands/execute/scroll.ts
driver/lib/driver.ts
driver/tslint.json

fixes https://github.com/appium-userland/appium-flutter-driver/issues/329

fix: revert * 1000 change for scroll

---

README.md

https://github.com/appium-userland/appium-flutter-driver/issues/349

docs: remove durationMilliseconds from flutter:waitFor

---

README.md
driver/lib/commands/execute/scroll.ts

Added an optional 'timeout' parameter for scrollIntoView as in flutter driver.

added timeout parameter for scrollIntoView

---

driver/lib/sessions/observatory.ts

Maybe better than `match` error message

chore: raise another error message

---

README.md
driver/CHANGELOG.md
driver/lib/commands/clipboard.ts
driver/lib/driver.ts

closes https://github.com/appium-userland/appium-flutter-driver/issues/316

feat: always call set/get clipboard from the base driver

---

README.md
driver/CHANGELOG.md
driver/lib/driver.ts
driver/lib/sessions/android.ts
driver/lib/sessions/ios.ts
driver/lib/sessions/session.ts

Allow a session to start without app starting for no `app` and `packageName` or `bundleId`

feat: allow a session starts without any apps

---

driver/lib/commands/execute/scroll.ts

possible idea for https://github.com/appium-userland/appium-flutter-driver/issues/372

feat: add timeout for scrollUntilVisible/scrollUntilTapable

---

driver/lib/sessions/observatory.ts

https://github.com/appium-userland/appium-flutter-driver/issues/439

chroe: add debug log

---

.gitignore
finder/dotnet/AppiumFlutterFinder/AppiumFlutterFinder.csproj
finder/dotnet/AppiumFlutterFinder/FlutterBy.cs
finder/dotnet/AppiumFlutterFinder/FlutterDriver.cs
finder/dotnet/AppiumFlutterFinder/FlutterElement.cs
finder/dotnet/AppiumFlutterFinder/FlutterElementFactory.cs
finder/dotnet/AppiumFlutterFinder/License.md
finder/dotnet/AppiumFlutterFinder/Readme.md
finder/dotnet/AppiumFlutterFinderTests/AppiumFlutterFinderTests.csproj
finder/dotnet/AppiumFlutterFinderTests/FlutterFinderTests.cs
finder/dotnet/AppiumFlutterFinderTests/Usings.cs
finder/dotnet/DotNetAppiumFlutterFinder.sln

I've added .net finder for flutter. Closes #81

add dotnet support Closes

---

driver/lib/driver.ts

https://github.com/appium-userland/appium-flutter-driver/issues/496

feat: proxy orientation to NATIVE_APP

---

driver/npm-shrinkwrap.json

Got a bit different package diff from this morning. let me push again to see the published module

chore: update npm-shrinkwrap

---

.github/workflows/publish.yml
driver/.releaserc
driver/npm-shrinkwrap.json
driver/package.json
driver/release.sh

https://github.com/appium-userland/appium-flutter-driver/issues/530

ci: add semantics-release and a job

---

README.md

With reference to the comment on this PR (https://github.com/appium/appium-flutter-driver/pull/540), I now updated the license for this https://github.com/5v1988/appium-flutter-client
Thank you!

Java alternative client for Appium Flutter Driver

---

README.md
driver/CHANGELOG.md
driver/lib/driver.ts

https://github.com/appium/appium-flutter-driver/issues/553#issuecomment-1712817263

feat: add skipAttachObservatoryUrl

---

.github/workflows/nodejs.yml

remove unnecessary npm install as this file

ci: nodejs.yml

---

driver/lib/commands/clipboard.ts
driver/lib/commands/context.ts
driver/lib/commands/execute.ts
driver/lib/commands/gesture.ts
driver/lib/commands/screen.ts
driver/lib/driver.ts
driver/lib/sessions/android.ts
driver/lib/sessions/base64url.ts
driver/lib/sessions/ios.ts
driver/lib/sessions/observatory.ts
driver/lib/sessions/session.ts
driver/package.json
driver/tsconfig.json

Also tuned project dependencies, so we don't keep any unused stuff there

fix: Varios typescript fixes

---

driver/package.json

as same as https://github.com/appium/appium-safari-driver/pull/97
Unit tests work, then this pr is ok.

test: fix npm run test

---

driver/npm-shrinkwrap.json
driver/package.json
driver/release.sh

```
% git grep 'appium-android-driver'
driver/npm-shrinkwrap.json:        "appium-android-driver": "^7.5.1",
driver/npm-shrinkwrap.json:    "node_modules/appium-android-driver": {
driver/npm-shrinkwrap.json:      "resolved": "https://registry.npmjs.org/appium-android-driver/-/appium-android-driver-7.8.1.tgz",
driver/npm-shrinkwrap.json:        "appium-android-driver": "^7.8.1",
driver/npm-shrinkwrap.json:    "node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver": {
driver/npm-shrinkwrap.json:      "resolved": "https://registry.npmjs.org/appium-android-driver/-/appium-android-driver-7.8.1.tgz",
driver/npm-shrinkwrap.json:    "appium-android-driver": {
driver/npm-shrinkwrap.json:      "resolved": "https://registry.npmjs.org/appium-android-driver/-/appium-android-driver- …
```

chore: remove appium-android-driver as no references

---

finder/kotlin/src/main/kotlin/pro/truongsinh/appium_flutter/FlutterFinder.kt
finder/kotlin/src/main/kotlin/pro/truongsinh/appium_flutter/finder/serializer.kt

kotlin: fix syntax of kotlin suggested by AS

---

driver/lib/commands/context.ts

closes https://github.com/appium/appium-flutter-driver/issues/267

chore: add logs in context change

---

README.md

docs: address appium-flutter-integration-driver

---

README.md

Commit 8b36a395ee179c848839cd54516ff2788f6c2011 moved the location of the example file. This PR adjusts sources to changes.

docs: update example reference
